services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=library
      - DB_HOST=db
      - JWT_SECRET=jkdgaiue6auedgdaiwud7267
    volumes:
      - .:/app
    container_name: library-sequelize
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always